export enum UserType {
    TYPE_STUDENT = "TYPE_STUDENT",
    TYPE_EMPLOYEE = "TYPE_EMPLOYEE"
}

export enum Role {
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_NIGHT_DUTY = "ROLE_NIGHT_DUTY",
    ROLE_HEAD = "ROLE_HEAD",
    ROLE_CARETAKER = "ROLE_CARETAKER",
    ROLE_DIRECTOR = "ROLE_DIRECTOR"
}