import { cardOutline, lockClosedOutline, mailOutline } from "ionicons/icons";

export const LABEL_FOR_INPUTS = {
    cardId: "Номер пропуска",
    password: "Пароль",
    email: "Электронная почта",
    passwordRepeat: "Повторите пароль",
    cardNumber: "Номер пропускной карты",
    surname: "Фамилия",
    name: "Имя",
    patronymic: "Отчество",
    passportSeries: "Серия паспорта",
    passportNumber: "Номер паспорта",
    passportIssueDate: "Дата выдачи паспорта",
    passportIssuePlace: "Кем выдан паспорт",
    birthPlace: "Место рождения",
    residentialAddress: "Адрес прописки",
    startDate: "Дата начала действия договора",
    expiryDate: "Дата окончания действия договора",
    dateOfBirth: "Дата рождения",
    phoneNumber: "Номер телефона",
    yearOfFinish: "Дата окончания",
    dayOfLeisure: "День недели",
    timeOfLeisure: "Время проведения",
    nameOfLeisure: "Название кружка",
    passportId: "Идентификационный номер паспорта",
    aboutCollege: "Откуда узнал о колледже",
    hobbies: "Хобби",
    workplace: "Место работы",
    contractId: "Идентификатор договора",
    nameBy: "Имя (бел.)",
    surnameBy: "Фамилия (бел.)",
    patronymicBy: "Отчество (бел.)",
    group: "Группа",
    graduationYear: "Год получения аттестата",
    gradePointAverage: "Средний балл аттестата",
    room: {
        number: "Номер комнаты",
        capacity: "Вместимость комнаты",
        floor: "Этаж"
    }
};
export const PLACEHOLDER_FOR_INPUT = {
    cardId: "15100039",
    password: "**********",
    email: 'user@gmail.com',
    passwordRepeat: "**********",
    cardNumber: "123456",
    surname: "Иванов",
    name: "Иван",
    patronymic: "Иванович",
    passportSeries: "МС",
    passportNumber: "1234567",
    passportIssueDate: "01.01.1961",
    passportIssuePlace: "Молодечненским РОВД Минской области",
    birthPlace: "Республика Беларусь, г. Минск, ул. Сурганова, д. 50",
    residentialAddress: "222307, Минская обл., г. Молодечно, ул. Иванова, д. 1, кв. 1",
    startDate: "01.01.1961",
    expiryDate: "01.01.1965",
    dateOfBirth: "01.01.1965",
    phoneNumber: "375 (33) 349 94 09",
    yearOfFinish: "01.01.1965",
    dayOfLeisure: "Понедельник",
    timeOfLeisure: "12:00",
    nameOfLeisure: "IT-Кружок",
    passportId: "7977246A001PB2",
    aboutCollege: "От друзей",
    hobbies: "Танцы",
    workplace: "",
    contractId: "",
    nameBy: "Имя (бел.)",
    surnameBy: "Фамилия (бел.)",
    patronymicBy: "Отчество (бел.)",
    group: "ИТ134",
    graduationYear: 2021,
    gradePointAverage: 7.2,
    room : {
        number: "313",
        floor: "2",
        capacity: "4"
    }
};

export const ICON_FOR_INPUTS = {
    cardId: cardOutline,
    password: lockClosedOutline,
    email: mailOutline
};
